name: Export Firebase to JSON

on:
  schedule:
    - cron: "*/5 * * * *"   # প্রতি 5 মিনিটে
  workflow_dispatch:

jobs:
  export:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Fetch Firebase Data
        run: |
          curl -o matches.json https://sportix-webs-default-rtdb.firebaseio.com/matches.json

      - name: Create data.json
        run: |
          echo '{ "matches":' > data.json
          cat matches.json >> data.json
          echo '}' >> data.json

      - name: Commit and Push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add data.json
          git commit -m "Auto update data.json from Firebase" || echo "No changes"
          git push
