name: Export Firebase to JSON

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  export:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Fetch Firebase Matches
        run: |
          curl -s "${{ secrets.FIREBASE_URL }}" > matches_raw.json

      - name: Create Pretty JSON
        run: |
          jq ". as \$data | {matches: \$data}" matches_raw.json > data.json

      - name: Commit & Push if Changed
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add data.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto update data.json"
          git push
